#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class EmailAddress : System.Runtime.Serialization.ISerializable
	{
		private int _emailAddressID;
		public virtual int EmailAddressID
		{
			get
			{
				return this._emailAddressID;
			}
			set
			{
				this._emailAddressID = value;
			}
		}
		
		private string _emailAddress1;
		public virtual string EmailAddress1
		{
			get
			{
				return this._emailAddress1;
			}
			set
			{
				this._emailAddress1 = value;
			}
		}
		
		private bool _isHTML;
		public virtual bool IsHTML
		{
			get
			{
				return this._isHTML;
			}
			set
			{
				this._isHTML = value;
			}
		}
		
		private int _personID;
		public virtual int PersonID
		{
			get
			{
				return this._personID;
			}
			set
			{
				this._personID = value;
			}
		}
		
		private byte _sortOrder;
		public virtual byte SortOrder
		{
			get
			{
				return this._sortOrder;
			}
			set
			{
				this._sortOrder = value;
			}
		}
		
		private Person _person;
		public virtual Person Person
		{
			get
			{
				return this._person;
			}
			set
			{
				this._person = value;
			}
		}
		
		#region ISerializable Implementation
		
		public EmailAddress()
		{
		}
		
		protected EmailAddress(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.EmailAddressID = info.GetInt32("EmailAddressID");
			this.EmailAddress1 = info.GetString("EmailAddress1");
			this.IsHTML = info.GetBoolean("IsHTML");
			this.PersonID = info.GetInt32("PersonID");
			this.SortOrder = info.GetByte("SortOrder");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("EmailAddressID", this.EmailAddressID, typeof(int));
			info.AddValue("EmailAddress1", this.EmailAddress1, typeof(string));
			info.AddValue("IsHTML", this.IsHTML, typeof(bool));
			info.AddValue("PersonID", this.PersonID, typeof(int));
			info.AddValue("SortOrder", this.SortOrder, typeof(byte));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
