#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Glyphicon
	{
		private int _glyphiconID;
		public virtual int GlyphiconID
		{
			get
			{
				return this._glyphiconID;
			}
			set
			{
				this._glyphiconID = value;
			}
		}
		
		private string _glyphicon1;
		public virtual string Glyphicon1
		{
			get
			{
				return this._glyphicon1;
			}
			set
			{
				this._glyphicon1 = value;
			}
		}
		
		private IList<Link> _links = new List<Link>();
		public virtual IList<Link> Links
		{
			get
			{
				return this._links;
			}
		}
		
		private IList<LinkGroup> _linkGroups = new List<LinkGroup>();
		public virtual IList<LinkGroup> LinkGroups
		{
			get
			{
				return this._linkGroups;
			}
		}
		
	}
}
#pragma warning restore 1591
