#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class LinkPermission
	{
		private int _linkPermissionID;
		public virtual int LinkPermissionID
		{
			get
			{
				return this._linkPermissionID;
			}
			set
			{
				this._linkPermissionID = value;
			}
		}
		
		private int _permissionID;
		public virtual int PermissionID
		{
			get
			{
				return this._permissionID;
			}
			set
			{
				this._permissionID = value;
			}
		}
		
		private int _linkID;
		public virtual int LinkID
		{
			get
			{
				return this._linkID;
			}
			set
			{
				this._linkID = value;
			}
		}
		
		private bool _isDeny;
		public virtual bool IsDeny
		{
			get
			{
				return this._isDeny;
			}
			set
			{
				this._isDeny = value;
			}
		}
		
		private Permission _permission;
		public virtual Permission Permission
		{
			get
			{
				return this._permission;
			}
			set
			{
				this._permission = value;
			}
		}
		
		private Link _link;
		public virtual Link Link
		{
			get
			{
				return this._link;
			}
			set
			{
				this._link = value;
			}
		}
		
	}
}
#pragma warning restore 1591
