#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class LinkGroup
	{
		private int _linkGroupID;
		public virtual int LinkGroupID
		{
			get
			{
				return this._linkGroupID;
			}
			set
			{
				this._linkGroupID = value;
			}
		}
		
		private string _linkGroupName;
		public virtual string LinkGroupName
		{
			get
			{
				return this._linkGroupName;
			}
			set
			{
				this._linkGroupName = value;
			}
		}
		
		private int? _glyphiconID;
		public virtual int? GlyphiconID
		{
			get
			{
				return this._glyphiconID;
			}
			set
			{
				this._glyphiconID = value;
			}
		}
		
		private int _sortOrder;
		public virtual int SortOrder
		{
			get
			{
				return this._sortOrder;
			}
			set
			{
				this._sortOrder = value;
			}
		}
		
		private string _currentModulePattern;
		public virtual string CurrentModulePattern
		{
			get
			{
				return this._currentModulePattern;
			}
			set
			{
				this._currentModulePattern = value;
			}
		}
		
		private bool _showInMobileNav;
		public virtual bool ShowInMobileNav
		{
			get
			{
				return this._showInMobileNav;
			}
			set
			{
				this._showInMobileNav = value;
			}
		}
		
		private Glyphicon _glyphicon;
		public virtual Glyphicon Glyphicon
		{
			get
			{
				return this._glyphicon;
			}
			set
			{
				this._glyphicon = value;
			}
		}
		
		private IList<Link> _links = new List<Link>();
		public virtual IList<Link> Links
		{
			get
			{
				return this._links;
			}
		}
		
	}
}
#pragma warning restore 1591
