#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class MessageRecipient
	{
		private long _recipientID;
		public virtual long RecipientID
		{
			get
			{
				return this._recipientID;
			}
			set
			{
				this._recipientID = value;
			}
		}
		
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private long _messageID;
		public virtual long MessageID
		{
			get
			{
				return this._messageID;
			}
			set
			{
				this._messageID = value;
			}
		}
		
		private DateTime? _readDate;
		public virtual DateTime? ReadDate
		{
			get
			{
				return this._readDate;
			}
			set
			{
				this._readDate = value;
			}
		}
		
		private bool _isStarred;
		public virtual bool IsStarred
		{
			get
			{
				return this._isStarred;
			}
			set
			{
				this._isStarred = value;
			}
		}
		
		private DateTime _sentDate;
		public virtual DateTime SentDate
		{
			get
			{
				return this._sentDate;
			}
			set
			{
				this._sentDate = value;
			}
		}
		
		private Message _message;
		public virtual Message Message
		{
			get
			{
				return this._message;
			}
			set
			{
				this._message = value;
			}
		}
		
	}
}
#pragma warning restore 1591
