#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class Message
	{
		private long _messageID;
		public virtual long MessageID
		{
			get
			{
				return this._messageID;
			}
			set
			{
				this._messageID = value;
			}
		}
		
		private string _body;
		public virtual string Body
		{
			get
			{
				return this._body;
			}
			set
			{
				this._body = value;
			}
		}
		
		private long? _parentMessageID;
		public virtual long? ParentMessageID
		{
			get
			{
				return this._parentMessageID;
			}
			set
			{
				this._parentMessageID = value;
			}
		}
		
		private int? _fromID;
		public virtual int? FromID
		{
			get
			{
				return this._fromID;
			}
			set
			{
				this._fromID = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private Message _message2;
		public virtual Message ParentMessage
		{
			get
			{
				return this._message2;
			}
			set
			{
				this._message2 = value;
			}
		}
		
		private IList<Message> _messages = new List<Message>();
		public virtual IList<Message> Messages
		{
			get
			{
				return this._messages;
			}
		}
		
		private IList<MessageRecipient> _messageRecipients = new List<MessageRecipient>();
		public virtual IList<MessageRecipient> MessageRecipients
		{
			get
			{
				return this._messageRecipients;
			}
		}
		
	}
}
#pragma warning restore 1591
