#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	public partial class NewUserMapping
	{
		private int _newUserMappingID;
		public virtual int NewUserMappingID
		{
			get
			{
				return this._newUserMappingID;
			}
			set
			{
				this._newUserMappingID = value;
			}
		}
		
		private int _roleID;
		public virtual int RoleID
		{
			get
			{
				return this._roleID;
			}
			set
			{
				this._roleID = value;
			}
		}
		
		private int _clubID;
		public virtual int ClubID
		{
			get
			{
				return this._clubID;
			}
			set
			{
				this._clubID = value;
			}
		}
		
		private Role _role;
		public virtual Role Role
		{
			get
			{
				return this._role;
			}
			set
			{
				this._role = value;
			}
		}
		
	}
}
#pragma warning restore 1591
