#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class PhoneNumber : System.Runtime.Serialization.ISerializable
	{
		private int _phoneNumberID;
		public virtual int PhoneNumberID
		{
			get
			{
				return this._phoneNumberID;
			}
			set
			{
				this._phoneNumberID = value;
			}
		}
		
		private string _tenDigit;
		public virtual string TenDigit
		{
			get
			{
				return this._tenDigit;
			}
			set
			{
				this._tenDigit = value;
			}
		}
		
		private string _extension;
		public virtual string Extension
		{
			get
			{
				return this._extension;
			}
			set
			{
				this._extension = value;
			}
		}
		
		private int _personID;
		public virtual int PersonID
		{
			get
			{
				return this._personID;
			}
			set
			{
				this._personID = value;
			}
		}
		
		private byte _sortOrder;
		public virtual byte SortOrder
		{
			get
			{
				return this._sortOrder;
			}
			set
			{
				this._sortOrder = value;
			}
		}
		
		private Person _person;
		public virtual Person Person
		{
			get
			{
				return this._person;
			}
			set
			{
				this._person = value;
			}
		}
		
		#region ISerializable Implementation
		
		public PhoneNumber()
		{
		}
		
		protected PhoneNumber(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.PhoneNumberID = info.GetInt32("PhoneNumberID");
			this.TenDigit = info.GetString("TenDigit");
			this.Extension = info.GetString("Extension");
			this.PersonID = info.GetInt32("PersonID");
			this.SortOrder = info.GetByte("SortOrder");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("PhoneNumberID", this.PhoneNumberID, typeof(int));
			info.AddValue("TenDigit", this.TenDigit, typeof(string));
			info.AddValue("Extension", this.Extension, typeof(string));
			info.AddValue("PersonID", this.PersonID, typeof(int));
			info.AddValue("SortOrder", this.SortOrder, typeof(byte));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
