#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class Player : System.Runtime.Serialization.ISerializable
	{
		private int _playerID;
		public virtual int PlayerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private int _personID;
		public virtual int PersonID
		{
			get
			{
				return this._personID;
			}
			set
			{
				this._personID = value;
			}
		}
		
		private Person _person;
		public virtual Person Person
		{
			get
			{
				return this._person;
			}
			set
			{
				this._person = value;
			}
		}
		
		private IList<Transaction> _transactions = new List<Transaction>();
		public virtual IList<Transaction> Transactions
		{
			get
			{
				return this._transactions;
			}
		}
		
		private IList<PlayerPass> _playerPasses = new List<PlayerPass>();
		public virtual IList<PlayerPass> PlayerPasses
		{
			get
			{
				return this._playerPasses;
			}
		}
		
		private IList<TeamPlayer> _teamPlayers = new List<TeamPlayer>();
		public virtual IList<TeamPlayer> TeamPlayers
		{
			get
			{
				return this._teamPlayers;
			}
		}
		
		private IList<Guardian> _guardians = new List<Guardian>();
		public virtual IList<Guardian> Guardians
		{
			get
			{
				return this._guardians;
			}
		}
		
		private IList<Attendance> _attendances = new List<Attendance>();
		public virtual IList<Attendance> Attendances
		{
			get
			{
				return this._attendances;
			}
		}
		
		#region ISerializable Implementation
		
		public Player()
		{
		}
		
		protected Player(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.PlayerID = info.GetInt32("PlayerID");
			this.PersonID = info.GetInt32("PersonID");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("PlayerID", this.PlayerID, typeof(int));
			info.AddValue("PersonID", this.PersonID, typeof(int));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
