#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class RegistrationRule : System.Runtime.Serialization.ISerializable
	{
		private int _registrationRuleID;
		public virtual int RegistrationRuleID
		{
			get
			{
				return this._registrationRuleID;
			}
			set
			{
				this._registrationRuleID = value;
			}
		}
		
		private int? _oldTeamID;
		public virtual int? OldTeamID
		{
			get
			{
				return this._oldTeamID;
			}
			set
			{
				this._oldTeamID = value;
			}
		}
		
		private int _newTeamID;
		public virtual int NewTeamID
		{
			get
			{
				return this._newTeamID;
			}
			set
			{
				this._newTeamID = value;
			}
		}
		
		private DateTime _registrationOpens;
		public virtual DateTime RegistrationOpens
		{
			get
			{
				return this._registrationOpens;
			}
			set
			{
				this._registrationOpens = value;
			}
		}
		
		private DateTime _registrationCloses;
		public virtual DateTime RegistrationCloses
		{
			get
			{
				return this._registrationCloses;
			}
			set
			{
				this._registrationCloses = value;
			}
		}
		
		private DateTime? _dateOfBirthCutoff;
		public virtual DateTime? DateOfBirthCutoff
		{
			get
			{
				return this._dateOfBirthCutoff;
			}
			set
			{
				this._dateOfBirthCutoff = value;
			}
		}
		
		private Team _team;
		public virtual Team OldTeam
		{
			get
			{
				return this._team;
			}
			set
			{
				this._team = value;
			}
		}
		
		private Team _team1;
		public virtual Team NewTeam
		{
			get
			{
				return this._team1;
			}
			set
			{
				this._team1 = value;
			}
		}
		
		#region ISerializable Implementation
		
		public RegistrationRule()
		{
		}
		
		protected RegistrationRule(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.RegistrationRuleID = info.GetInt32("RegistrationRuleID");
			this.OldTeamID = (int?)info.GetValue("OldTeamID", typeof(int?));
			this.NewTeamID = info.GetInt32("NewTeamID");
			this.RegistrationOpens = (DateTime)info.GetValue("RegistrationOpens", typeof(DateTime));
			this.RegistrationCloses = (DateTime)info.GetValue("RegistrationCloses", typeof(DateTime));
			this.DateOfBirthCutoff = (DateTime?)info.GetValue("DateOfBirthCutoff", typeof(DateTime?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("RegistrationRuleID", this.RegistrationRuleID, typeof(int));
			info.AddValue("OldTeamID", this.OldTeamID, typeof(int?));
			info.AddValue("NewTeamID", this.NewTeamID, typeof(int));
			info.AddValue("RegistrationOpens", this.RegistrationOpens, typeof(DateTime));
			info.AddValue("RegistrationCloses", this.RegistrationCloses, typeof(DateTime));
			info.AddValue("DateOfBirthCutoff", this.DateOfBirthCutoff, typeof(DateTime?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
