#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class TeamSchedule : System.Runtime.Serialization.ISerializable
	{
		private int _teamScheduleID;
		public virtual int TeamScheduleID
		{
			get
			{
				return this._teamScheduleID;
			}
			set
			{
				this._teamScheduleID = value;
			}
		}
		
		private string _eventName;
		public virtual string EventName
		{
			get
			{
				return this._eventName;
			}
			set
			{
				this._eventName = value;
			}
		}
		
		private DateTime _startDate;
		public virtual DateTime StartDate
		{
			get
			{
				return this._startDate;
			}
			set
			{
				this._startDate = value;
			}
		}
		
		private DateTime _endDate;
		public virtual DateTime EndDate
		{
			get
			{
				return this._endDate;
			}
			set
			{
				this._endDate = value;
			}
		}
		
		private int _teamID;
		public virtual int TeamID
		{
			get
			{
				return this._teamID;
			}
			set
			{
				this._teamID = value;
			}
		}
		
		private DateTime? _rSVPBy;
		public virtual DateTime? RSVPBy
		{
			get
			{
				return this._rSVPBy;
			}
			set
			{
				this._rSVPBy = value;
			}
		}
		
		private bool _isActive;
		public virtual bool IsActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				this._isActive = value;
			}
		}
		
		private int _createUserID;
		public virtual int CreateUserID
		{
			get
			{
				return this._createUserID;
			}
			set
			{
				this._createUserID = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private int? _modifyUserID;
		public virtual int? ModifyUserID
		{
			get
			{
				return this._modifyUserID;
			}
			set
			{
				this._modifyUserID = value;
			}
		}
		
		private DateTime? _modifyDate;
		public virtual DateTime? ModifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				this._modifyDate = value;
			}
		}
		
		private int? _deleteUserID;
		public virtual int? DeleteUserID
		{
			get
			{
				return this._deleteUserID;
			}
			set
			{
				this._deleteUserID = value;
			}
		}
		
		private DateTime? _deleteDate;
		public virtual DateTime? DeleteDate
		{
			get
			{
				return this._deleteDate;
			}
			set
			{
				this._deleteDate = value;
			}
		}
		
		private Team _team;
		public virtual Team Team
		{
			get
			{
				return this._team;
			}
			set
			{
				this._team = value;
			}
		}
		
		private IList<Attendance> _attendances = new List<Attendance>();
		public virtual IList<Attendance> Attendances
		{
			get
			{
				return this._attendances;
			}
		}
		
		#region ISerializable Implementation
		
		public TeamSchedule()
		{
		}
		
		protected TeamSchedule(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.TeamScheduleID = info.GetInt32("TeamScheduleID");
			this.EventName = info.GetString("EventName");
			this.StartDate = (DateTime)info.GetValue("StartDate", typeof(DateTime));
			this.EndDate = (DateTime)info.GetValue("EndDate", typeof(DateTime));
			this.TeamID = info.GetInt32("TeamID");
			this.RSVPBy = (DateTime?)info.GetValue("RSVPBy", typeof(DateTime?));
			this.IsActive = info.GetBoolean("IsActive");
			this.CreateUserID = info.GetInt32("CreateUserID");
			this.CreateDate = (DateTime)info.GetValue("CreateDate", typeof(DateTime));
			this.ModifyUserID = (int?)info.GetValue("ModifyUserID", typeof(int?));
			this.ModifyDate = (DateTime?)info.GetValue("ModifyDate", typeof(DateTime?));
			this.DeleteUserID = (int?)info.GetValue("DeleteUserID", typeof(int?));
			this.DeleteDate = (DateTime?)info.GetValue("DeleteDate", typeof(DateTime?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("TeamScheduleID", this.TeamScheduleID, typeof(int));
			info.AddValue("EventName", this.EventName, typeof(string));
			info.AddValue("StartDate", this.StartDate, typeof(DateTime));
			info.AddValue("EndDate", this.EndDate, typeof(DateTime));
			info.AddValue("TeamID", this.TeamID, typeof(int));
			info.AddValue("RSVPBy", this.RSVPBy, typeof(DateTime?));
			info.AddValue("IsActive", this.IsActive, typeof(bool));
			info.AddValue("CreateUserID", this.CreateUserID, typeof(int));
			info.AddValue("CreateDate", this.CreateDate, typeof(DateTime));
			info.AddValue("ModifyUserID", this.ModifyUserID, typeof(int?));
			info.AddValue("ModifyDate", this.ModifyDate, typeof(DateTime?));
			info.AddValue("DeleteUserID", this.DeleteUserID, typeof(int?));
			info.AddValue("DeleteDate", this.DeleteDate, typeof(DateTime?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
