#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class TournamentTeam : System.Runtime.Serialization.ISerializable
	{
		private int _tournamentTeamID;
		public virtual int TournamentTeamID
		{
			get
			{
				return this._tournamentTeamID;
			}
			set
			{
				this._tournamentTeamID = value;
			}
		}
		
		private string _teamName;
		public virtual string TeamName
		{
			get
			{
				return this._teamName;
			}
			set
			{
				this._teamName = value;
			}
		}
		
		private int _tournamentBracketID;
		public virtual int TournamentBracketID
		{
			get
			{
				return this._tournamentBracketID;
			}
			set
			{
				this._tournamentBracketID = value;
			}
		}
		
		private bool _active;
		public virtual bool Active
		{
			get
			{
				return this._active;
			}
			set
			{
				this._active = value;
			}
		}
		
		private int _createUserID;
		public virtual int CreateUserID
		{
			get
			{
				return this._createUserID;
			}
			set
			{
				this._createUserID = value;
			}
		}
		
		private DateTime _createDate;
		public virtual DateTime CreateDate
		{
			get
			{
				return this._createDate;
			}
			set
			{
				this._createDate = value;
			}
		}
		
		private int? _modifyUserID;
		public virtual int? ModifyUserID
		{
			get
			{
				return this._modifyUserID;
			}
			set
			{
				this._modifyUserID = value;
			}
		}
		
		private DateTime? _modifyDate;
		public virtual DateTime? ModifyDate
		{
			get
			{
				return this._modifyDate;
			}
			set
			{
				this._modifyDate = value;
			}
		}
		
		private int? _deleteUserID;
		public virtual int? DeleteUserID
		{
			get
			{
				return this._deleteUserID;
			}
			set
			{
				this._deleteUserID = value;
			}
		}
		
		private DateTime? _deleteDate;
		public virtual DateTime? DeleteDate
		{
			get
			{
				return this._deleteDate;
			}
			set
			{
				this._deleteDate = value;
			}
		}
		
		private TournamentBracket _tournamentBracket;
		public virtual TournamentBracket TournamentBracket
		{
			get
			{
				return this._tournamentBracket;
			}
			set
			{
				this._tournamentBracket = value;
			}
		}
		
		private IList<TournamentRoster> _tournamentRosters = new List<TournamentRoster>();
		public virtual IList<TournamentRoster> TournamentRosters
		{
			get
			{
				return this._tournamentRosters;
			}
		}
		
		#region ISerializable Implementation
		
		public TournamentTeam()
		{
		}
		
		protected TournamentTeam(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.TournamentTeamID = info.GetInt32("TournamentTeamID");
			this.TeamName = info.GetString("TeamName");
			this.TournamentBracketID = info.GetInt32("TournamentBracketID");
			this.Active = info.GetBoolean("Active");
			this.CreateUserID = info.GetInt32("CreateUserID");
			this.CreateDate = (DateTime)info.GetValue("CreateDate", typeof(DateTime));
			this.ModifyUserID = (int?)info.GetValue("ModifyUserID", typeof(int?));
			this.ModifyDate = (DateTime?)info.GetValue("ModifyDate", typeof(DateTime?));
			this.DeleteUserID = (int?)info.GetValue("DeleteUserID", typeof(int?));
			this.DeleteDate = (DateTime?)info.GetValue("DeleteDate", typeof(DateTime?));
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("TournamentTeamID", this.TournamentTeamID, typeof(int));
			info.AddValue("TeamName", this.TeamName, typeof(string));
			info.AddValue("TournamentBracketID", this.TournamentBracketID, typeof(int));
			info.AddValue("Active", this.Active, typeof(bool));
			info.AddValue("CreateUserID", this.CreateUserID, typeof(int));
			info.AddValue("CreateDate", this.CreateDate, typeof(DateTime));
			info.AddValue("ModifyUserID", this.ModifyUserID, typeof(int?));
			info.AddValue("ModifyDate", this.ModifyDate, typeof(DateTime?));
			info.AddValue("DeleteUserID", this.DeleteUserID, typeof(int?));
			info.AddValue("DeleteDate", this.DeleteDate, typeof(DateTime?));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
