#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class TournamentRoster : System.Runtime.Serialization.ISerializable
	{
		private int _playerID;
		public virtual int PlayerID
		{
			get
			{
				return this._playerID;
			}
			set
			{
				this._playerID = value;
			}
		}
		
		private string _fName;
		public virtual string FName
		{
			get
			{
				return this._fName;
			}
			set
			{
				this._fName = value;
			}
		}
		
		private string _lName;
		public virtual string LName
		{
			get
			{
				return this._lName;
			}
			set
			{
				this._lName = value;
			}
		}
		
		private DateTime _dateOfBirth;
		public virtual DateTime DateOfBirth
		{
			get
			{
				return this._dateOfBirth;
			}
			set
			{
				this._dateOfBirth = value;
			}
		}
		
		private int _tournamentTeamID;
		public virtual int TournamentTeamID
		{
			get
			{
				return this._tournamentTeamID;
			}
			set
			{
				this._tournamentTeamID = value;
			}
		}
		
		private TournamentTeam _tournamentTeam;
		public virtual TournamentTeam TournamentTeam
		{
			get
			{
				return this._tournamentTeam;
			}
			set
			{
				this._tournamentTeam = value;
			}
		}
		
		#region ISerializable Implementation
		
		public TournamentRoster()
		{
		}
		
		protected TournamentRoster(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.PlayerID = info.GetInt32("PlayerID");
			this.FName = info.GetString("FName");
			this.LName = info.GetString("LName");
			this.DateOfBirth = (DateTime)info.GetValue("DateOfBirth", typeof(DateTime));
			this.TournamentTeamID = info.GetInt32("TournamentTeamID");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("PlayerID", this.PlayerID, typeof(int));
			info.AddValue("FName", this.FName, typeof(string));
			info.AddValue("LName", this.LName, typeof(string));
			info.AddValue("DateOfBirth", this.DateOfBirth, typeof(DateTime));
			info.AddValue("TournamentTeamID", this.TournamentTeamID, typeof(int));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
