#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using TrackrModels;

namespace TrackrModels	
{
	[System.Serializable()]
	public partial class Tournament : System.Runtime.Serialization.ISerializable
	{
		private int _tournamentID;
		public virtual int TournamentID
		{
			get
			{
				return this._tournamentID;
			}
			set
			{
				this._tournamentID = value;
			}
		}
		
		private int _clubID;
		public virtual int ClubID
		{
			get
			{
				return this._clubID;
			}
			set
			{
				this._clubID = value;
			}
		}
		
		private string _name;
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		
		private Club _club;
		public virtual Club Club
		{
			get
			{
				return this._club;
			}
			set
			{
				this._club = value;
			}
		}
		
		private IList<TournamentBracket> _tournamentBrackets = new List<TournamentBracket>();
		public virtual IList<TournamentBracket> TournamentBrackets
		{
			get
			{
				return this._tournamentBrackets;
			}
		}
		
		#region ISerializable Implementation
		
		public Tournament()
		{
		}
		
		protected Tournament(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			this.TournamentID = info.GetInt32("TournamentID");
			this.ClubID = info.GetInt32("ClubID");
			this.Name = info.GetString("Name");
			CustomizeDeserializationProcess(info, context);
		}
		
		public virtual void GetObjectData(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context)
		{
			info.AddValue("TournamentID", this.TournamentID, typeof(int));
			info.AddValue("ClubID", this.ClubID, typeof(int));
			info.AddValue("Name", this.Name, typeof(string));
			CustomizeSerializationProcess(info, context);
		}
		
		partial void CustomizeSerializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		partial void CustomizeDeserializationProcess(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
		#endregion
	}
}
#pragma warning restore 1591
