// Code is generated by Telerik Data Access Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using TrackrModels;

namespace Trackr
{
    public partial class GlyphiconRepository : OpenAccessBaseRepository<TrackrModels.Glyphicon, TrackrModels.UserManagement>
    {

    }

    public partial class LinkRepository : OpenAccessBaseRepository<TrackrModels.Link, TrackrModels.UserManagement>
    {

    }

    public partial class LinkGroupRepository : OpenAccessBaseRepository<TrackrModels.LinkGroup, TrackrModels.UserManagement>
    {

    }

    public partial class LinkPermissionRepository : OpenAccessBaseRepository<TrackrModels.LinkPermission, TrackrModels.UserManagement>
    {

    }

    public partial class NewUserMappingRepository : OpenAccessBaseRepository<TrackrModels.NewUserMapping, TrackrModels.UserManagement>
    {

    }

	public partial class PermissionRepository : OpenAccessBaseRepository<TrackrModels.Permission, TrackrModels.UserManagement>
    {
	
    }

	public partial class RoleRepository : OpenAccessBaseRepository<TrackrModels.Role, TrackrModels.UserManagement>
    {
	
    }

	public partial class ScopeRepository : OpenAccessBaseRepository<TrackrModels.Scope, TrackrModels.UserManagement>
    {
	
    }

	public partial class ScopeAssignmentRepository : OpenAccessBaseRepository<TrackrModels.ScopeAssignment, TrackrModels.UserManagement>
    {
	
    }

	public partial class WebUserRepository : OpenAccessBaseRepository<TrackrModels.WebUser, TrackrModels.UserManagement>
    {
	
    }
}
